categories = {
    'Alimentare': ['PIZZERIA',
                   'PASTICERIA',
                   'RISTORANTE',
                   'TRATTORIA',
                   'COFFEE',
                   'Glovo',
                   'BAR',
                   'OLD WILD WEST',
                   'DELIVEROO',
                   'AUTOGRILL',
                   'MAMMA MIA',
                   'BURGERKINGBK25456',
                   'CAFFE',
                   'CAFE',
                   'PIZZA',
                   'SUSHI',
                   'CANEPHORA',
                   'CENA',
                   'BEER',
                   'GELATERIA',
                   'FORNO',
                   'BONIN',
                   'ALJANO',
                   'FORNERIA',
                   'PUB',
                   'SEGAFREDO',
                   'CIRCOLO ARCI I VIZI DE CORREGGIO',
                   'DISPENSA EMILIA',
                   'RAMENGO',
                   'BIRRERIA',
                   'VERONAFIERE SPA VERONA',
                   'VERONAFIERE S.P.A. VERONA',
                   'PIZZIKOTTO MODENA',
                   'PANE AMORE E FANTASIA CARPI',
                   'Deliveroo',
                   'LA PERLA SNC CARPI',
                   'IL PANE DEL FORNAIO CARPI',
                   'DA CICCIO DI MOTTOLA'
                   'EL ZIRMO'],
    'Spesa': ['IPER', 'INTERSPAR', 'SUPERMERCATO'],
    'Parrucchiere': ['PARRUCCHIERI', 'TRENTANOVE HAIR'],
    'Benzina': ['DISTRIBUTORE', 'BPETROL', 'CARBURANTI', 'PETROLI', 'ENI'],
    'Affitto': ['Affitto'],
    'Viaggi': ['Booking.com', 'ESP', 'PRT', 'BOOKING', 'WeRoad', 'Trenitalia', 'GIULIA BOZEGLAV', 'Marrakech', 'ANMAN',
               'RYANAIR'],
    'Vestiti': ['GLOBO', 'Estasi', 'Elena Messori', 'MISTER TENNIS SRL'],
    'NowTv': ['Sky'],
    'Internet': ['VODAFONE'],
    'Palestra': ['LA PATRIA'],
    'Satispay': ['SATISPAY'],
    'Telepass': ['TELEPASS'],
    'Mediche': ['SACCAN', 'FARMACIA', '3C SALUTE'],
    'Amazon': ['Amazon', 'AMZN', 'AWS EMEA'],
    'Paypal': ['PAYPAL'],
    'Prelievo': ['PRELIEVO'],
    'Cellulare': ['ILIAD'],
    'Multe': ['CBILL'],
    'Concerti': ['Ticketmaster', 'TicketOne'],
    'Bollette': ['ENELENERGIA', 'ENEL ENERGIA SPA', 'Acqua'],
    'PasticcieriaModenese': ['PASTICCERIA MODENESE CARPI'],
    'Other': [],
    'AIS': ['AISITALIA', 'Radikon', 'Associazione Italiana Sommelier', 'ASSOCIAZIONE ITALIANA SOMMELIER',
            'In.Pro.Di. Inghirami Produzione Distribuzione S.p.a.'],
    'Assicurazione': ['Assicurazione'],
    'Auto': ['MELONI AUTO CENTRO RE NOVELLARA'],
    'Stipendio': ['EMOLUMENTI'],
    'AltreEntrate': ["BONIFICO A CREDITO ORDINATO DA ARTIOLI ROBERTO PIRONDI PAOLA"]
}

totalDf = {
    'Alimentare': 'UsciteNecessarie',
    'Spesa': 'UsciteNecessarie',
    'Parrucchiere': 'UsciteStileVita',
    'Benzina': 'UsciteNecessarie',
    'Affitto': 'UsciteNecessarie',
    'Viaggi': 'UsciteStileVita',
    'Auto': 'UsciteStileVita',
    'Multe': 'UsciteStileVita',
    'Internet': 'UsciteNecessarie',
    'Palestra': 'UsciteStileVita',
    'Vestiti': 'UsciteStileVita',
    'Bollette': 'UsciteNecessarie',
    'Other': 'UsciteStileVita',
    'Concerti': 'UsciteStileVita',
    'Satispay': 'UsciteStileVita',
    'Telepass': 'UsciteNecessarie',
    'Mediche': 'UsciteNecessarie',
    'NowTv': 'UsciteStileVita',
    'AIS': 'UsciteStileVita',
    'Amazon': 'UsciteStileVita',
    'Paypal': 'UsciteStileVita',
    'Cellulare': 'UsciteNecessarie',
    'PasticcieriaModenese': 'UsciteNecessarie',
    'Assicurazione': 'UsciteNecessarie',
    'Stipendio': 'Entrate',
    'Prelievo': 'UsciteStileVita',
    'AltreEntrate': 'Entrate',
    'ZTotaleB1': 'Entrate',
    'ZTotaleB2': 'UsciteNecessarie',
    'ZTotaleB4': 'UsciteStileVita',
}

patternToExcludeConto = r'(RICARICA|Ricarica|Investimenti|ADDEBITO MESE CARTA EGO)'
patternToExcludeCarta = r'(PAYPAL|Ricarica|Investimenti)'
