categories = {
    'Alimentare': ['PIZZERIA',
                   'PASTICERIA',
                   'RISTORANTE',
                   'TRATTORIA',
                   'COFFEE',
                   'Glovo',
                   'BAR',
                   'OLD WILD WEST',
                   'DELIVEROO',
                   'AUTOGRILL',
                   'MAMMA MIA',
                   'BURGERKINGBK25456',
                   'CAFFE',
                   'CAFE',
                   'PIZZA',
                   'SUSHI',
                   'CANEPHORA',
                   'CENA',
                   'BEER',
                   'GELATERIA',
                   'FORNO',
                   'BONIN',
                   'ALJANO',
                   'FORNERIA',
                   'PUB',
                   'SEGAFREDO',
                   'CIRCOLO ARCI I VIZI DE CORREGGIO',
                   'DISPENSA EMILIA',
                   'RAMENGO',
                   'BIRRERIA',
                   'VERONAFIERE SPA VERONA',
                   'VERONAFIERE S.P.A. VERONA',
                   'PIZZIKOTTO MODENA',
                   'PANE AMORE E FANTASIA CARPI',
                   'Deliveroo',
                   'LA PERLA SNC CARPI',
                   'IL PANE DEL FORNAIO CARPI',
                   'DA CICCIO DI MOTTOLA'
                   'EL ZIRMO'],
    'Spesa': ['IPER', 'INTERSPAR', 'SUPERMERCATO'],
    'Parrucchiere': ['PARRUCCHIERI', 'TRENTANOVE HAIR'],
    'Benzina': ['DISTRIBUTORE', 'BPETROL', 'CARBURANTI', 'PETROLI', 'ENI'],
    'Affitto': ['Affitto'],
    'Viaggi': ['Booking.com', 'ESP', 'PRT', 'BOOKING', 'WeRoad', 'Trenitalia', 'GIULIA BOZEGLAV', 'Marrakech', 'ANMAN',
               'RYANAIR'],
    'Vestiti': ['GLOBO', 'Estasi', 'Elena Messori', 'MISTER TENNIS SRL'],
    'NowTv': ['Sky'],
    'Internet': ['VODAFONE'],
    'Palestra': ['LA PATRIA'],
    'Satispay': ['SATISPAY'],
    'Telepass': ['TELEPASS'],
    'Mediche': ['SACCAN', 'FARMACIA', '3C SALUTE'],
    'Amazon': ['Amazon', 'AMZN', 'AWS EMEA'],
    'Paypal': ['PAYPAL'],
    'Prelievo': ['PRELIEVO'],
    'Cellulare': ['ILIAD'],
    'Multe': ['CBILL'],
    'Concerti': ['Ticketmaster', 'TicketOne'],
    'Bollette': ['ENELENERGIA', 'ENEL ENERGIA SPA', 'Acqua'],
    'PasticcieriaModenese': ['PASTICCERIA MODENESE CARPI'],
    'Other': [],
    'AIS': ['AISITALIA', 'Radikon', 'Associazione Italiana Sommelier', 'ASSOCIAZIONE ITALIANA SOMMELIER',
            'In.Pro.Di. Inghirami Produzione Distribuzione S.p.a.'],
    'Assicurazione': ['Assicurazione'],
    'Auto': ['MELONI AUTO CENTRO RE NOVELLARA'],
    'Stipendio': ['EMOLUMENTI'],
    'Contributo': ["BONIFICO A CREDITO ORDINATO DA ARTIOLI ROBERTO PIRONDI PAOLA"]
}

totalDf = {
        'Alimentare': 'Necessarie',
        'Spesa': 'Necessarie',
        'Parrucchiere': 'StileVita',
        'Benzina': 'Necessarie',
        'Affitto': 'Necessarie',
        'Viaggi': 'StileVita',
        'Auto': 'StileVita',
        'Multe': 'StileVita',
        'Internet': 'Necessarie',
        'Palestra': 'StileVita',
        'Vestiti': 'StileVita',
        'Bollette': 'Necessarie',
        'Other': 'StileVita',
        'Concerti': 'StileVita',
        'Satispay': 'StileVita',
        'Telepass': 'Necessarie',
        'Mediche': 'Necessarie',
        'NowTv': 'StileVita',
        'AIS': 'StileVita',
        'Amazon': 'StileVita',
        'Paypal': 'StileVita',
        'Cellulare': 'Necessarie',
        'PasticcieriaModenese': 'Necessarie',
        'Assicurazione': 'Necessarie',
        'Stipendio': 'Stipendio',
        'Prelievo': 'StileVita',
        'Contributo': 'Contributo',
        'ZTotaleB1': 'ZStipendio',
        'ZTotaleB2': 'Necessarie',
        'ZTotaleB4': 'StileVita',
}